### ISSUE TITLE
Broken demo in Firefox 

### ISSUE THREAD

**Issue by stof** [andreypopp/react-router-page-transition#4]
In firefox, your demo is broken:

- there is no animation when going to the about page (it is loaded without animation)
- going back to the main page does not work, for any link (the about page is still displayed)

**Comment by mattapperson** [comment]
Seeing this too...

**Comment by mattapperson** [comment]
Looks like its just the CSS... only has -webkit not -moz props... as such it wont work in IE ether. Module works though.

**Comment by STRML** [comment]
Thanks for this. Just removed the prefixes, it's working fine in FF now.

**Comment by mattapperson** [comment]
Fwiw without any prefix it will only work in newer browsers. For best results use no prefix + -moz + -webkit

**Comment by STRML** [comment]
I know - but it'll be fine IE10 and up. Good enough for me.
