### ISSUE TITLE
ES6 import + Browserify = JSX Parse Error

### ISSUE THREAD

**Issue by Wildhoney** [andreypopp/react-router-page-transition#7]
@andreypopp I'm trying to import the module using the module loader syntax:

```javascript
import { AnimatedLocations } from 'react-router-page-transition';
```

However, when I try to transpile that using Browserify + Babelify, I get an error:

> Error: Parsing file /Users/atimberlake/Webroot/Mobile/node_modules/react-router-page-transition/index.js: Unexpected token (46:6)

Which points to the JSX inside of the `react-router-page-transition` module. It seems as though Browerify doesn't process modules inside of `node_modules`.

Do you have any pointers to get this to transpile? Спасибо.

**Comment by STRML** [comment]
Unfortunately the `main` import on the package.json should be `bundle.js`, not `index.js`, and this is causing your problem.

This is such a simple module that I generally recommend just copy/pasting the `<AnimatedLocations>` source into your own project somewhere.

**Comment by Wildhoney** [comment]
Thanks @STRML I'm looking at `TransitionGroup` instead, which seems to do the trick:

```javascript
render() {
    const name = this.context.router.getCurrentPath();
    return (
        <TransitionGroup component="div" transitionName="moveUp">
            <RouteHandler key={name} />
        </TransitionGroup>
    );
}
```

Which works fine with a typical ES6 `import`: `import TransitionGroup from 'react/lib/ReactCSSTransitionGroup'` :+1:

**Comment by STRML** [comment]
You should be able to use this module directly via npm now via a github url. I have not yet published it to NPM because I want to change the name (conflicts with react-router).

If you use the module directly you get some of the nice features, like `popStateTransitionName` and `noTransition`/`transitionName` on links.
